<a href="https://colab.research.google.com/github/kalai-glitch/git_cds/blob/main/Newnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
#creating array
arr=np.array([])
print(arr)
type(arr)
#nd n dimendional aaray

[]


numpy.ndarray

In [ ]:
arr=np.array([3,4,5,6,7,8])
print(arr)
print(type(arr))

[3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [ ]:
colors=np.array(("red","blue","yellow","green"))
print(colors)
print(type(colors))

['red' 'blue' 'yellow' 'green']
<class 'numpy.ndarray'>


In [ ]:
list=[6,7,8,9]
list1=np.array(list)
print(list1)

[6 7 8 9]


In [ ]:
#only list and tuples u create an array
tuple=((23,5,67,89))
tuple1=np.array(tuple)
print(tuple1)

[23  5 67 89]


In [ ]:
#1 d array
arr=([6,7,2,34.9,'hello'])
arr1=np.array(arr)
print(arr1)
print('dimension of array is',arr1.ndim)
print("elemts in array is",arr1.size)
print(len(arr1))
print("data type of elements in array is",arr1.dtype)

['6' '7' '2' '34.9' 'hello']
dimension of array is 1
elemts in array is 5
5
data type of elements in array is <U32


#2d array matrics
arr_2d=np.array([[2,3,4],[5,6,7],[8,9,5]])
print(arr_2d)

In [ ]:
#2d array matrics
arr_2d=np.array([[2,3,4],[5,6,7],[8,9,5]])
print(arr_2d)

[[2 3 4]
 [5 6 7]
 [8 9 5]]


In [ ]:
arr_2dd=np.array([[4,5,6,7],[1,2,3,4],[4,5,6,6],[2,3,4,5]])
print(arr_2dd)
print(type(arr_2dd))
print('dimension of array is',arr_2dd.ndim)
print("elements in array",arr_2dd.size)
print("order of matrix",arr_2dd.shape)

[[4 5 6 7]
 [1 2 3 4]
 [4 5 6 6]
 [2 3 4 5]]
<class 'numpy.ndarray'>
dimension of array is 2
elements in array 16
order of matrix (4, 4)


In [ ]:
arr_3d=np.array([[[2,3,6,7],[3,4,5,6],[2,3,4,5]]])
print(arr_3d)
print("dimension is",arr_3d.ndim)
print("order of matrix",arr_3d.shape)

[[[2 3 6 7]
  [3 4 5 6]
  [2 3 4 5]]]
dimension is 3
order of matrix (1, 3, 4)


In [ ]:
import numpy as np

# create a 3D array with shape (2, 3, 4)
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
arr = np.array(nested_list)

print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(100,151)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [ ]:
np.arange(2,21,2) #start,stop,step

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
np.full((2,2),(10))

array([[10, 10],
       [10, 10]])

In [ ]:
np.full((3,3),(6))

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [ ]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
np.linspace(1,100,num=10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]),
 np.float64(11.0))

In [ ]:
np.random.randint(1,100,10)

array([78, 51, 47, 72, 14, 61, 38, 73, 36, 68])

In [ ]:
np.random.randint(20,60,size=(2,2))

array([[54, 52],
       [39, 27]])

In [ ]:
np.random.randint(20,size=(3,3))

array([[ 0,  1,  9],
       [ 4,  7, 12],
       [19,  6, 18]])

In [ ]:
np.random.rand(10) #generate 10 random number from 0 to 1

array([0.83138345, 0.74760169, 0.09760224, 0.4795168 , 0.87584806,
       0.15426228, 0.04738977, 0.98420898, 0.44769612, 0.44521878])

In [ ]:
np.random.rand(4,4) #create 2d array with random value  from 0 to 1

array([[0.40283339, 0.39864555, 0.94979376, 0.26358613],
       [0.5090878 , 0.18830808, 0.11520359, 0.6804996 ],
       [0.32695072, 0.12421081, 0.06420976, 0.559639  ],
       [0.67967716, 0.13233877, 0.26806872, 0.05043228]])

In [ ]:
np.random.randn(3,4) #craete array with normal distribution value within range [-3,3]

array([[-2.44033967, -0.16387051, -0.82987417,  1.34094974],
       [ 0.44624722,  0.38246974, -0.08072489, -0.05478081],
       [ 0.29083659,  0.52940178,  0.57940932, -1.54203716]])

In [ ]:
arr=np.random.randint(1,1000,10)
print(arr)

[ 12 247 333 528 226 386 202 358 820 672]


In [ ]:
np.max(arr)


np.int64(820)

In [ ]:
np.argmax(arr)

np.int64(8)

In [ ]:
np.argmin(arr)

np.int64(0)

In [ ]:
value=np.arange(1,100)
print(value)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
value[3]

np.int64(4)

In [ ]:
value[1:5]

array([2, 3, 4, 5])

In [ ]:
value[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
#create 2d array
arr_2d=np.array([[2,3,4],[5,6,4],[6,7,8]])
arr_2d

array([[2, 3, 4],
       [5, 6, 4],
       [6, 7, 8]])

In [ ]:
arr_2d[[1]]

array([[5, 6, 4]])

In [ ]:
arr_2d[[0,2]]

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
arr_2d[2][1] #2 row and 1 column fetching 7

np.int64(7)

In [ ]:
#fetch first column all row included
arr_2d[:,[0]]

array([[2],
       [5],
       [6]])

In [ ]:
arr_2d[[1],:]

array([[5, 6, 4]])

In [ ]:
arr_2d[:,[1,2]]

array([[3, 4],
       [6, 4],
       [7, 8]])

In [ ]:
arr1=np.array([2,3,4,5,6,7])
arr2=np.array([4,6,7,7,4,2])
print(arr1,arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1+5)

[2 3 4 5 6 7] [4 6 7 7 4 2]
[ 6  9 11 12 10  9]
[-2 -3 -3 -2  2  5]
[ 8 18 28 35 24 14]
[0.5        0.5        0.57142857 0.71428571 1.5        3.5       ]
[ 7  8  9 10 11 12]
